### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by LolTrippyy** [uen/Leveling-System#108]
I add this straight to my /addons/ folder and it just doesn't seem to work. It makes no errors, or show any sign of life. I can't seem to use it for code or anything either.  It's dormant pretty much. Does nothing. I can't seem to find anyone with the same issue and was hoping someone could help out.

**Comment by uen** [comment]
You probably installed it incorrectly. Provide more info and you can get some help! The addon does work
