### ISSUE TITLE
You have earned 0 xp.

### ISSUE THREAD

**Issue by GranDaddySmoke** [uen/Leveling-System#94]
Hey Vrondakis!

I used this addon prevously on my DarkRP server with massive success,.

I am now trying to install it on a new server and I am running into a problem.

Players receive 0 xp per cycle, i'd assume the same problem from the previous post in here.

Can we please get a fix and not let the only good XP system for Garrys Mod go to waste!

Thanks.

**Comment by versuche** [comment]
i have that error 2 :( pls fix

**Comment by chesiren** [comment]
@GranDaddySmoke @versuche 
Hi !
I made a version that works with darkrp 2.7.0 : https://github.com/chesiren/DarkRP-Leveling-System-2.7.0

**Comment by vrondakis** [comment]
@chesiren Please make a PR!

**Comment by chesiren** [comment]
@vrondakis pull request done

**Comment by vrondakis** [comment]
Use the 'fix' branch which has @chesiren merged in, it has a few code issues but should be fine until I get round to changing it: https://github.com/vrondakis/Leveling-System/tree/fix
Good job :D
